version: '3.8'
services:
  mentorly:
    image: 18-alpine3.16
    container_name: mentorly
    volumes:
      - webroot:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - persistent:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  persistent:
  webroot:
